language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: MzjoM0ic9kkS/0uBfuOscSObgj3ju/u31RBmqgSbdp4Bh4b4KsFl5UZWHGFR8raUJQVaB0vgyCCDiDshz7I3I30xusa/xNdffykFHlZQjm5RYNZZ9uhk3Ilc5is37TT121KQPEEPxHYS+C9E2uKQqjZmDJ7ji3ghYCKzO9R7HFZjWpaWrGKkgYiqB+JChc6Z/bPzZtfd8xa8R+lVET9bZae9xPIXlNdYPypxKWcqPdUQ//cVY6pSRnbpsOLUyfBjUkSgVLbSKPEKLquWJlZ5Ba1OVn0RQNXuwa0We5/sZ9Oa7fES/VoA6E28KY/2A7EvM8uZ7bM/+PqxetzdZ4/uu1bOvH7r5N9HE17EaxnnNzMoetvfgqbt6wu73pT85sKyjSEPTsM1nky30JVUGvexTaeN9gg1xDHebVAjeHZjxsllFtgLFOnqoDdsFQDO8UxU58tmpMYxw7sI+ldECqX1eFz2f9B7XriwAbUhk60iow6A2HinuxQk0IRqAkOFSmn7WGroj8lt4zznNqV6l/UP/Wx0vuriFFR209E+bowiwpmbn256TkJeHn6zNylY/xgHgO5oSNNKsTNfpg3h0blQO/2zoFC+x8LcM6wES8xFlpwMRqh9iT6DLOlCqOl4jBtZHfPPDJVsfw3LPoQs9Y3xmXtbqIdZiW7uaRg5sWpyric=
  