language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: YHeTP2rAdlpvozXQUUIPJD3DxVmsMdv01qVZh8YTW1WBzqBkO28oFuqPs6q6BwErBsguDCKvTW6Q0Mv4xwNiYsrSAWhn9kCwTl0BMNSY3eNSrWGuwIgVZj4a7arDfwGj8sIJow+Fpzp8YuK5TXXIQf8Rmv+uOBn+0T0ailhLWfyfkuFQJ7pXucEchh7IdqPWkZW/ERpmBzjEGi/ntoykNatlMQSRLP3FFYLDkNDOIyhKu0u63Q29MuRhz/hVfqKL6A+8OMd3AQS3q7daTTFsCG7wXF9E6J3sluA0l4CzxvT9fhqAqsqKyuaG8YFD6V/efYDeL9Jc27jNncRSWtXTxS5GKq8ix/vFHXUhUgVM23IFJR8uCbm+7w5SOejY85XAplnvvbmQndpZSGI8qeVk8SAJMha1bq0kis9d9959F5A/nS6qv83YA2FyZUu1I3IJXdOMnpT31jF7MS9yWXPdVzbiQjBOmJn5YTnHFivHcmdnInOE22nS3mxlFns8UATm4bHJz0YPNFi80/pjOH6JkflGLQ18dxJBZWuwxRXJw26kBCJoic3bscfcAyCrjHn7Tt14HOR5kSfZhxxt+Y5fs0EiYV6m2JzPbHs9H9aaqbKwkkxMghClGDqq8CvRhDqaSQBorfxj6PQTAOUa8GNehZjC9aFI9uF/YHetIQVFlDc=
  - secure: pVLPK11LZXB6SCqlxAYQxzkSbcW2yLByqopiLDMmEtEt0/moNyUX6fpTXGBP9ZcTE7DlN3FZ7Q4Ngn8bClkjN56xayBBIz51TeikrRTnM9zf8VWY5mFoBVJ2ZdUP5svorIF9CxKW7A1soq5r3PcbPKvm9YaXkncYejoxcsun3foHcASSMPztZzx3ioWmdHhB1X9OXs73lu305iIvolIDKaWi7NRYFW5qeqs933YL+AfEzzZpmiXT8zils+awOFBWT2+sn2Mn6cz77UvDOSED7xvWQIizMrvpibvER6EXCPxDc0Lyc2a3NoJMOWVqAoOZDDVdBPXqxmyTX+o1OYY4PNFKygkDphWH34mz9lauY5Qqx1LrEChrgzE73hLTKuvlJXpVt+5FfjRoUJdZ5+bk2JWCoVZf8YyjCMV937TJxcLHh3QyqHWQkFHwJdH1ezv+19JhIXIBxFu5w3wwfsflN9XPB5/3pWgnIcAEwZJb+yT8TVoBfV9wazGZ8VMiREE45Ek0rLm89IW2YJ+XJ83PeHK3Wsmhk8zDEIUGkrKzUItYAc4Iwf7Pt515mFg2/+u/TUrufTE0OPYaDwYqfyDgqcTQlt8fj9lY8oChS61yhLXB06t+TlPhsAIZ7+5GwybXsj0PRy1CPRLe9jvyglgD0U1Nn31ijDs9DXqYd0EoG+0=
