language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: YHeTP2rAdlpvozXQUUIPJD3DxVmsMdv01qVZh8YTW1WBzqBkO28oFuqPs6q6BwErBsguDCKvTW6Q0Mv4xwNiYsrSAWhn9kCwTl0BMNSY3eNSrWGuwIgVZj4a7arDfwGj8sIJow+Fpzp8YuK5TXXIQf8Rmv+uOBn+0T0ailhLWfyfkuFQJ7pXucEchh7IdqPWkZW/ERpmBzjEGi/ntoykNatlMQSRLP3FFYLDkNDOIyhKu0u63Q29MuRhz/hVfqKL6A+8OMd3AQS3q7daTTFsCG7wXF9E6J3sluA0l4CzxvT9fhqAqsqKyuaG8YFD6V/efYDeL9Jc27jNncRSWtXTxS5GKq8ix/vFHXUhUgVM23IFJR8uCbm+7w5SOejY85XAplnvvbmQndpZSGI8qeVk8SAJMha1bq0kis9d9959F5A/nS6qv83YA2FyZUu1I3IJXdOMnpT31jF7MS9yWXPdVzbiQjBOmJn5YTnHFivHcmdnInOE22nS3mxlFns8UATm4bHJz0YPNFi80/pjOH6JkflGLQ18dxJBZWuwxRXJw26kBCJoic3bscfcAyCrjHn7Tt14HOR5kSfZhxxt+Y5fs0EiYV6m2JzPbHs9H9aaqbKwkkxMghClGDqq8CvRhDqaSQBorfxj6PQTAOUa8GNehZjC9aFI9uF/YHetIQVFlDc=
